version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: sidebar
    # volumes:
    #   - db-data:/var/lib/data
  web:
    build: .
    command: bash -c "npm start"
    image: welp-sidebar
    # volumes:
    #   - .:/app
    ports:
      - "3002:3002"
    depends_on:
      - db
    environment:
      # DATABASE_URL: postgres://postgres@db
      DB_HOST: db
    # links:
    #   - db
# volumes:
#   db-data:
# networks:
#   webnet:
